// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEahzTQtOkVCsXJ9yPwM-6PTsYqH8lbOs',
    appId: '1:281901233587:web:45b721eb276c0e561087c6',
    messagingSenderId: '281901233587',
    projectId: 'flutter-ticketing-app',
    authDomain: 'flutter-ticketing-app.firebaseapp.com',
    storageBucket: 'flutter-ticketing-app.firebasestorage.app',
    measurementId: 'G-JRN47GLX3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzRdREPg25EVx0mXMrDB5PzrPmVojeH8s',
    appId: '1:281901233587:android:6525a26b6999d8431087c6',
    messagingSenderId: '281901233587',
    projectId: 'flutter-ticketing-app',
    storageBucket: 'flutter-ticketing-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrg4IqF_yLfBeLpBeQdyuk_rgWNzwHXHM',
    appId: '1:281901233587:ios:8b299a78b11a07791087c6',
    messagingSenderId: '281901233587',
    projectId: 'flutter-ticketing-app',
    storageBucket: 'flutter-ticketing-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTicketingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrg4IqF_yLfBeLpBeQdyuk_rgWNzwHXHM',
    appId: '1:281901233587:ios:8b299a78b11a07791087c6',
    messagingSenderId: '281901233587',
    projectId: 'flutter-ticketing-app',
    storageBucket: 'flutter-ticketing-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTicketingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEahzTQtOkVCsXJ9yPwM-6PTsYqH8lbOs',
    appId: '1:281901233587:web:9b85d984d94ee2cf1087c6',
    messagingSenderId: '281901233587',
    projectId: 'flutter-ticketing-app',
    authDomain: 'flutter-ticketing-app.firebaseapp.com',
    storageBucket: 'flutter-ticketing-app.firebasestorage.app',
    measurementId: 'G-RNH1HLM4LH',
  );
}
